import type { Metadata } from "next";
import { Playfair_Display, Nunito } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "./components/navbar";
import Footer from "./components/footer";


const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Vicnasol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <Head>
      <title>{metadata.title as string}</title>
      </Head>
      <body className={`${playfair.variable} ${nunito.variable}`}>
        <Navbar />
        <div className="min-h-screen min-w-screen bg-green-50">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
